### ISSUE TITLE
WASM support

### ISSUE THREAD

**Issue by walidlahba** [Zekfad/fetch_api#4]
Hey,

Current Version relies on dart:js  package:js and dart:html which it incompatible with WASM.

Thank you

**Comment by Zekfad** [comment]
It's actually supported in the repo code, I need to do a little clean up before publishing.
If you need WASM client right now, you can temporarily override dependency with git repo.

**Comment by Zekfad** [comment]
Published https://pub.dev/packages/fetch_api/versions/2.0.0-wasm

**Comment by walidlahba** [comment]
Amazing. Thank you
