### ISSUE TITLE
Runtime type cast error in WASM

### ISSUE THREAD

**Issue by vasilev** [Zekfad/fetch_api#5]
When [the example](https://github.com/Zekfad/fetch_api/blob/1.0.2/example/fetch_api_example.dart) is compiled to WASM, the error is thrown in browser:

```
Type '_Future<JSValue>' is not a subtype of type 'Future<String>' in type cast

    at main inner (https://testsite.tld/main.wasm:wasm-function[332]:0xd659)
    at closure wrapper at file:///usr/lib/dart/lib/_internal/wasm/lib/async_patch.dart:83:16 trampoline (https://testsite.tld/main.wasm:wasm-function[400]:0xed4b)
    at _RootZone.runUnary (https://testsite.tld/main.wasm:wasm-function[363]:0xe48f)
    at _Future._propagateToListeners (https://testsite.tld/main.wasm:wasm-function[344]:0xdf2c)
    at _Future._completeWithValue (https://testsite.tld/main.wasm:wasm-function[378]:0xe829)
    at closure wrapper at file:///usr/lib/dart/lib/async/future_impl.dart:721:29 trampoline (https://testsite.tld/main.wasm:wasm-function[393]:0xebaf)
    at _startMicrotaskLoop tear-off trampoline (https://testsite.tld/main.wasm:wasm-function[385]:0xe9cb)
    at _invokeCallback (https://testsite.tld/main.wasm:wasm-function[76]:0x8c96)
```

All the examples for both [fetch_api](https://github.com/Zekfad/fetch_api/tree/1.0.2/example/) and [fetch_client](https://github.com/Zekfad/fetch_client/tree/1.1.1/example/) do work OK then compiled to JS and fail when compiled to WASM with same type casting errors.
Tested with Dart SDK 3.4.1 and 3.4.0.

### How to reproduce

```sh
dart create -t web reprerror
cd reprerror/web
wget -O main.dart https://raw.githubusercontent.com/Zekfad/fetch_api/1.0.2/example/fetch_api_example.dart
cat > index.html << 'END'
<script type="module">
  import { instantiate, invoke } from "./main.mjs";
  const module = await WebAssembly.compileStreaming(fetch('main.wasm'));
  const instance = await instantiate(module);
  invoke(instance);
</script>
END
dart pub add fetch_api
dart compile wasm main.dart
python3 -m http.server
```

And point your browser to port 8000.

### Possible fixes

I'd suspect the WASM build has some kind of stricter typing than JS build, so need to insert explicit `.toDart` somewhere in `fetch_api` code (maybe conditionally, only for WASM).

**Comment by Zekfad** [comment]
Hi, thanks for the report.
Last time I checked wasm it was a beta, so things seem to change a little. I suspect it has to do with a few rare cases where we cast `JSPromise<JSString>` to `Futute<String>`.

E.g. here we chain future to apply cast to inner type:

https://github.com/Zekfad/fetch_api/blob/c672f97d0f598c8d2b1583f7b3143e7fc0c8e52d/lib/src/request/request.dart#L185-L186

and here we assert thet `JSString` is compatible with `String`:

https://github.com/Zekfad/fetch_api/blob/c672f97d0f598c8d2b1583f7b3143e7fc0c8e52d/lib/src/request/request.dart#L205-L206

`JSPromiseOr` on a first look, works with a `T extends JSAny?`, so we're not really asserting any types...

Could you please post demangled stack trace?

It also could be something about JS strings being opaque in Dart WASM runtime, while in Dart JS they can be safely cast to plain Dart Sting.

**Comment by Zekfad** [comment]
Fixed in 2.2.0 (fetch_client 2.1.2)

**Comment by vasilev** [comment]
https://github.com/Zekfad/fetch_api/commit/28540d69b1a079de889d9b4eded56416e06fc11d#diff-b638ef91065e4b4b618f886893d5bd8caade89a8e3c0bac2862774e369d42383L146-L148

Exactly ;)

---

Confirming, the WASM build works OK in v2.2.0.

Thank you @Zekfad for such a quick fix! 
And thank you for your projects!

**Comment by Zekfad** [comment]
You're welcome, @vasilev .
